import Head from 'next/head';
import Image from 'next/image';
import ClientLayout from '@/components/layout-client';

export default function checkout() {
  return (
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.png" />
      <title>Madrasda | Checkout</title>
    </Head>

    <ClientLayout>
        <main>
            <div className="min-w-screen min-h-screen bg-gray-50 py-5">
                <div className="px-5">
                    <div className="mb-2">
                        <a href="#" className="focus:outline-none hover:underline text-gray-500 text-sm"><i className="mdi mdi-arrow-left text-gray-400"></i>Back</a>
                    </div>
                    <div className="mb-2">
                        <h1 className="text-3xl text-primary md:ml-20 mt-10">ADD ADDRESS</h1>
                    </div>
                    <div className="mb-5 md:ml-20 text-gray-400">
                        <a href="./index.js" className="focus:outline-none hover:underline text-gray-500">Home</a> /  <span className="text-gray-600">Checkout</span>
                    </div>
                </div>
                <hr className="h-px md:ml-20 mr-12 ml-5 my-6 bg-black border-1 dark:bg-primary"></hr>
                <div className="w-full bg-white border-gray-200 px-5 py-10 text-gray-800 pr-12">
                    <div className="w-full">
                        <div className="-mx-3 md:ml-20 md:flex items-start">
                            {/* CART DETAILS */}
                            <div className="px-3 md:w-5/12">         
                                <div className="w-full flex items-center hover:bg-off-white rounded-lg">
                                    <div className="overflow-hidden rounded-lg w-2/12 h-2/12 bg-[#D9D9D9] border border-gray">
                                    <Image src="/vikram-tee.png" alt="ecommerce" width={1080} height={1920} className="object-contain object-center w-full h-full block" />
                                    </div>
                                    <div className="flex-grow pl-3 ml-4">
                                        <h6 className="font-medium text-2xl text-black">Round Neck Solid Mens T-Shirt</h6>
                                        <p className="text-gray">Vikram Collection</p>
                                        <p className="text-gray">Size-L</p>
                                        <p className="text-gray">Qty-1</p>
                                    </div>
                                    <div>
                                        <span class="font-medium text-black text-xl">₹699</span>
                                    </div>
                                    <div>
                                        <button class="font-medium text-gray text-xl ml-4 mr-4">x</button>
                                    </div>
                                </div>
                                <hr className="h-px my-6 border-[#D9D9D9] border-1 "></hr>
                                <div class="mb-6 pb-6 text-lg border-b border-[#D9D9D9] text-black">
                                    <div class="w-full flex mb-3 items-center">
                                        <div class="flex-grow">
                                            <span class="text-black">Subtotal</span>
                                        </div>
                                        <div class="pl-3">
                                            <span class="font-medium">₹699</span>
                                        </div>
                                    </div>
                                    <div class="w-full flex items-center">
                                        <div class="flex-grow">
                                            <span class="text-black">Shipping</span>
                                        </div>
                                        <div class="pl-3">
                                            <span class="font-medium">Free</span>
                                        </div>
                                    </div>
                                </div>
                                <div class="mb-6 pb-6 border-b border-gray md:border-none text-gray-800 text-xl">
                                    <div class="w-full flex items-center">
                                        <div class="flex-grow">
                                            <span class="text-gray-600">Total</span>
                                            <p className="text-sm text-gray">Including all taxes</p>
                                        </div>
                                        <div class="pl-3">
                                            <span class="font-medium text-gray text-sm">INR</span> <span class="font-medium text-2xl">₹699</span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {/* ADDRESS FORM */}
                            <div className="px-3 md:w-7/12 lg:pr-10">
                                <div className="mb-6">
                                    <h2 className="ml-2 mb-6 title-font font-medium text-xl">Email</h2>
                                    <div className="mb-2 ml-2 mt-1">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-black text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5" placeholder="Enter your Email Address"/>
                                    </div>
                                    <div className="flex ml-2">
                                        <div className="flex items-center h-5">
                                            <input id="helper-radio" aria-describedby="helper-radio-text" type="radio" value="" className="w-4 h-4 text-[#D9D9D9]"/>
                                            <label for="helper-radio" className="font-medium text-base text-[#D9D9D9] ml-2 ">Email me with news & offers</label>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <h2 className="ml-2 mb-6 title-font font-medium text-xl">Shipping Details</h2>
                                    <div className="mb-6 ml-2 mt-1 ">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5" placeholder="Country/Region"/>
                                    </div>
                                    <div className="mb-6 ml-2 mt-1 flex flex-row">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 mr-2" placeholder="First Name"/>
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 ml-2" placeholder="Last Name"/>
                                    </div>
                                    <div className="mb-6 ml-2 mt-1 ">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5" placeholder="Address Line 1"/>
                                    </div>
                                    <div className="mb-6 ml-2 mt-1 ">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5" placeholder="Address Line 2 (Optional)"/>
                                    </div>
                                    <div className="mb-6 ml-2 mt-1 flex flex-row">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 mr-2" placeholder="City"/>
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 mr-2 ml-2" placeholder="State"/>
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 ml-2" placeholder="Pincode"/>
                                    </div>
                                </div>
                                <div className="flex justify-end">
                                <button type="button" className="text-white bg-primary  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2">Proceed to Payment</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </ClientLayout>
    </>
  )
}
