import Head from 'next/head';
import Image from 'next/image';
import ClientLayout from '@/components/layout-client';
import { useRouter } from "next/router";
import { useEffect,useState,useContext } from 'react';
import { getRole, isTokenValid } from '@/utils/JWTVerifier';
import {UserContext} from "../../context/context";
import axios from 'axios';
import CartItem from '@/components/CartItem';
import { uuidv4 } from '@firebase/util';

export default function checkout() {
  const router = useRouter();
  let isReady = router.isReady;
  const ctx = useContext(UserContext);
  const [cart, setCart] = useState({});
  const [visible, setVisible] = useState(false);
  const [subTotal, setSubtotal] = useState(0);
  const [loading, setLoading] = useState(false);
  const [client, setClient] = useState(false);

  useEffect(() => {
        if (visible && !isTokenValid(localStorage.getItem("token"))) {
            router.push("/login")
        } else {
            if (ctx.cart.cartItems !== undefined) {
                const sum = ctx.cart.cartItems.reduce((prev, curr) => prev += curr.quantity * curr.product.total, 0);
                setSubtotal(sum);
            }
        }
    }, [ctx.cart])


  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
    setLoading(false);
      }, 1000);
  }, []);

  useEffect(() => {
    const jwtToken = localStorage.getItem('token');
    if(jwtToken && getRole(jwtToken) === "ROLE_ADMIN")
        router.push("/admin");
    if(jwtToken && getRole(jwtToken) === "ROLE_VENDOR")
        router.push("/vendor");
    if(jwtToken && isTokenValid(jwtToken))
        setClient(true);
    else
        setClient(false);
  }, [])

  if(loading && isReady)
  return (<div className='z-50 h-screen w-screen overflow-hidden'>
  <Image src="/loader.gif" width={1920} height={1080}/>
  </div>);

    return (
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.png" />
      <title>Madrasda | Checkout</title>
    </Head>

    <ClientLayout client={client}>
        <main>
            <div className="min-w-screen min-h-screen bg-gray-50 py-5">
                <div className="px-5">
                    <div className="mb-2">
                        <a href="#" className="focus:outline-none hover:underline text-gray-500 text-sm"><i className="mdi mdi-arrow-left text-gray-400"></i>Back</a>
                    </div>
                    <div className="mb-2">
                        <h1 className="text-3xl text-primary md:ml-20 mt-10">ADD ADDRESS</h1>
                    </div>
                    <div className="mb-5 md:ml-20 text-gray-400">
                        <a href="./index.js" className="focus:outline-none hover:underline text-gray-500">Home</a> /  <span className="text-gray-600">Checkout</span>
                    </div>
                </div>
                <hr className="h-px md:ml-20 mr-12 ml-5 my-6 bg-black border-1 dark:bg-primary"></hr>
                <div className="w-full bg-white border-gray-200 px-5 py-10 text-gray-800 pr-12">
                    <div className="w-full">
                        <div className="-mx-3 md:ml-20 md:flex items-start">
                            {/* CART DETAILS */}
                            <div className=" bg-[#D9D9D9] w-full p-5 rounded-lg">
                                <div className="px-3 w-full">
                                    {   ctx.cart && ctx.cart.cartItems &&
                                        ctx.cart.cartItems.map(item =>
                                            <CartItem
                                                key={uuidv4()}
                                                id={item.id}
                                                qty={item.quantity}
                                                product={item.product}
                                            />)
                                    }
                                    <hr className="h-px my-6 border-[#D9D9D9] border-1 "></hr>
                                    <div className="mb-6 pb-6 text-lg border-b border-[#D9D9D9] text-black">
                                        <div className="w-full flex mb-3 items-center">
                                            <div className="flex-grow">
                                                <span className="text-black">Subtotal</span>
                                            </div>
                                            <div className="pl-3">
                                                <span className="font-medium">₹{subTotal}</span>
                                            </div>
                                        </div>
                                        <div className="w-full flex items-center">
                                            <div className="flex-grow">
                                                <span className="text-black">Shipping</span>
                                            </div>
                                            <div className="pl-3">
                                                <span className="font-medium">Free</span>
                                            </div>
                                        </div>
                                    </div>
                                    <div
                                        className="mb-6 pb-6 border-b border-gray md:border-none text-gray-800 text-xl">
                                        <div className="w-full flex items-center">
                                            <div className="flex-grow">
                                                <span className="text-gray-600">Total</span>
                                                <p className="text-sm text-gray">Including all taxes</p>
                                            </div>
                                            <div className="pl-3">
                                                <span className="font-medium text-gray text-sm">INR</span> <span
                                                className="font-medium text-2xl">₹{subTotal}</span>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {/* ADDRESS FORM */}
                            <div className="px-3 md:w-7/12 lg:pr-10">
                                <div className="mb-6">
                                    <h2 className="ml-2 mb-6 title-font font-medium text-xl">Email</h2>
                                    <div className="mb-2 ml-2 mt-1">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-black text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5" placeholder="Enter your Email Address"/>
                                    </div>
                                    <div className="flex ml-2">
                                        <div className="flex items-center h-5">
                                            <input id="helper-radio" aria-describedby="helper-radio-text" type="radio" value="" className="w-4 h-4 text-[#D9D9D9]"/>
                                            <label for="helper-radio" className="font-medium text-base text-[#D9D9D9] ml-2 ">Email me with news & offers</label>
                                        </div>
                                    </div>
                                </div>
                                <div>
                                    <h2 className="ml-2 mb-6 title-font font-medium text-xl">Shipping Details</h2>
                                    <div className="mb-6 ml-2 mt-1 ">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5" placeholder="Country/Region"/>
                                    </div>
                                    <div className="mb-6 ml-2 mt-1 flex flex-row">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 mr-2" placeholder="First Name"/>
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 ml-2" placeholder="Last Name"/>
                                    </div>
                                    <div className="mb-6 ml-2 mt-1 ">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5" placeholder="Address Line 1"/>
                                    </div>
                                    <div className="mb-6 ml-2 mt-1 ">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5" placeholder="Address Line 2 (Optional)"/>
                                    </div>
                                    <div className="mb-6 ml-2 mt-1 flex flex-row">
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 mr-2" placeholder="City"/>
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 mr-2 ml-2" placeholder="State"/>
                                        <input type="text" className="bg-white border border-[#D9D9D9] text-white text-sm rounded-lg focus:ring-primary focus:border-[#D9D9D9] block w-full p-2.5 ml-2" placeholder="Pincode"/>
                                    </div>
                                </div>
                                <div className="flex justify-end">
                                <button type="button" className="text-white bg-primary  font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2">Proceed to Payment</button>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </ClientLayout>
    </>
  )
}
