import Head from 'next/head'
import Carousel from '@/components/carousel'
import Image from 'next/image'
import Link from 'next/link'
import ClientLayout from '@/components/layout-client'
import RightsideDisc from '@/components/rightside-disc'
import LeftsideDisc from '@/components/leftside-disc'
import { useRouter } from "next/router";
import { useEffect, useState, useContext } from 'react';
import {UserContext} from "../../context/context";
import { isTokenValid, getRole } from '@/utils/JWTVerifier';
import { uuidv4 } from '@firebase/util'
import HotSellers from '@/components/hotsellers-client'

export default function Home() {
  const router = useRouter();
  const ctx = useContext(UserContext);
  let isReady = router.isReady;
  const [details, setDetails] = useState(null);
  const [designs, setDesigns] = useState(null);
  const [loading, setLoading] = useState(false);
  const [client, setClient] = useState(false);
  const [allVendor, setAllVendor] = useState([]);

  
  useEffect(() => {
    setLoading(true);
    setTimeout(() => {
    setLoading(false);
      }, 1000);
  }, []);

  useEffect(() => {
    const jwtToken = localStorage.getItem('token');
    if(jwtToken && getRole(jwtToken) === "ROLE_ADMIN")
        router.push("/admin");
    if(jwtToken && getRole(jwtToken) === "ROLE_VENDOR")
        router.push("/vendor");
    if(jwtToken && isTokenValid(jwtToken))
        setClient(true);
    else
        setClient(false);
  }, []);

  if(loading && isReady)
  return (<div className='z-50 h-screen w-screen overflow-hidden'>
  <Image src="/loader.gif" width={1920} height={1080} className="object-cover object-center w-full h-full"/>
  </div>);


  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <title>Madrasda</title>
      </Head>
      
      <ClientLayout client={client}>
        <Carousel />
          <h1 className='font-algeria font-bold text-3xl my-10 px-10'>OFFICIAL MERCHANDISE</h1>
          
          {
            ctx.vendorList &&
            ctx.vendorList.map((vendor, index) => {
              if(index%2===0){
                return (
                  <RightsideDisc key={uuidv4} id={vendor.id} name={vendor.name} imgUrl={vendor.imgUrl} />
                )
              }else{
                return (
                  <LeftsideDisc key={uuidv4} id={vendor.id} name={vendor.name} imgUrl={vendor.imgUrl} />
                )
              }
            })
          }
      <HotSellers />
      </ClientLayout>
    </>
  )
}
