import Head from 'next/head'
import { Inter } from '@next/font/google'
import Link from 'next/link'
// import './ToggleSwitch.css'

const inter = Inter({ subsets: ['latin'] })

export default function Login() {
  return (
    <>
    <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <title>Madrasda | Login</title>
      </Head>
      <div className="bg-center bg-no-repeat bg-cover flex bg-[url(https://cdn.discordapp.com/attachments/812329575953858620/1078262102269104199/Login.png)] w-screen h-screen">
            <div className='w-full bg-cover bg-center flex-center flex-row bg-transparent max-w-md m-auto backdrop-blur-md bg-black/60 rounded-3xl drop-shadow-2xl py-8 px-16'>
            <div className="flex flex-wrap justify-center">
                <div className="w-24">
                    <img src="/logo.png" alt="LOGO"/>
                </div>
            </div>
            <div className='flex flex-wrap mt-2 justify-center'>
            </div>
            <h1 className='text-2xl text-white font-medium mt-2 mb-12 text-center'>
                LOGIN
            </h1>
                <form>
                    <div>
                        <label htmlFor='number' className='text-white'>Phone Number</label>
                        <input
                            type='phone number'
                            className={'w-full p-2 text-primary rounded-md outline-none text-sm transition duration-150 ease-in-out mb-4'}
                            id='number'
                            placeholder='+91XXXXXXXXXX'
                        />
                    </div>
                    {/* <div>
                        <label htmlFor='OTP' className='text-white'>OTP</label>
                        <input
                            type='otp'
                            className={'w-full p-2 text-primary rounded-md outline-none text-sm transition duration-150 ease-in-out mb-4'}
                            id='otp'
                            placeholder='otp'
                        />
                    </div> */}

                    <div className='flex justify-center items-center mt-4'>
                        <Link href="/">
                        <button className={`bg-[#A5153F] cursor-pointer py-2 px-5 text-l text-white rounded focus:outline-none `}>
                            Login
                        </button>
                        </Link>
                    </div>
                </form>
                <div className="w-100 underline text-white text-sm text-center mt-3">
                    <Link href="/vendor">
                    Click to Vendor Login
                    </Link>
                </div>
            <br/>
            </div>
        </div>
    </>
  )
}
