import Head from 'next/head';
import Image from 'next/image';
import ClientLayout from '@/components/layout-client';

export default function Cart() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <title>Madrasda | Cart</title>
      </Head>
          <div className="px-3 md:w-5/12">         
            <div className="w-full flex items-center hover:bg-off-white rounded-lg">
                <div className="overflow-hidden rounded-lg w-2/12 h-2/12 bg-[#D9D9D9] border border-gray">
                <Image src="/vikram-tee.png" alt="ecommerce" width={1080} height={1920} className="object-contain object-center w-full h-full block" />
                </div>
                <div className="flex-grow pl-3 ml-4">
                    <h6 className="font-medium text-2xl text-black">Round Neck Solid Mens T-Shirt</h6>
                    <p className="text-gray">Vikram Collection</p>
                    <p className="text-gray">Size-L</p>
                </div>
                <div>
                    <span class="font-medium text-black text-xl">₹699</span>
                </div>
                <div>
                    <button class="font-medium text-gray text-xl ml-4 mr-4">x</button>
                </div>
            </div>
            <hr className="h-px my-6 border-[#D9D9D9] border-1 "></hr>
            <div class="mb-6 pb-6 text-lg border-b border-[#D9D9D9] text-black">
                <div class="w-full flex mb-3 items-center">
                    <div class="flex-grow">
                        <span class="text-black">Subtotal</span>
                    </div>
                    <div class="pl-3">
                        <span class="font-medium">₹699</span>
                    </div>
                </div>
                <div class="w-full flex items-center">
                    <div class="flex-grow">
                        <span class="text-black">Shipping</span>
                    </div>
                    <div class="pl-3">
                        <span class="font-medium">Free</span>
                    </div>
                </div>
            </div>
            <div class="mb-6 pb-6 border-b border-gray md:border-none text-gray-800 text-xl">
                <div class="w-full flex items-center">
                    <div class="flex-grow">
                        <span class="text-gray-600">Total</span>
                        <p className="text-sm text-gray">Including all taxes</p>
                    </div>
                    <div class="pl-3">
                        <span class="font-medium text-gray text-sm">INR</span> <span class="font-medium text-2xl">₹699</span>
                    </div>
                </div>
            </div>
          </div>
          </>
)
}
