import Head from 'next/head';
import Image from 'next/image';

export default function Cart() {
  return (
    <>
      <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <title>MadrasDa | Cart</title>
      </Head>
          <div className="px-3 md:w-5/12">         
            
            <hr className="h-px my-6 border-[#D9D9D9] border-1 "></hr>
            <div className="mb-6 pb-6 text-lg border-b border-[#D9D9D9] text-black">
                <div className="w-full flex mb-3 items-center">
                    <div className="flex-grow">
                        <span className="text-black">Subtotal</span>
                    </div>
                    <div className="pl-3">
                        <span className="font-medium">₹699</span>
                    </div>
                </div>
                <div className="w-full flex items-center">
                    <div className="flex-grow">
                        <span className="text-black">Shipping</span>
                    </div>
                    <div className="pl-3">
                        <span className="font-medium">Free</span>
                    </div>
                </div>
            </div>
            <div className="mb-6 pb-6 border-b border-gray md:border-none text-gray-800 text-xl">
                <div className="w-full flex items-center">
                    <div className="flex-grow">
                        <span className="text-gray-600">Total</span>
                        <p className="text-sm text-gray">Including all taxes</p>
                    </div>
                    <div className="pl-3">
                        <span className="font-medium text-gray text-sm">INR</span> <span className="font-medium text-2xl">₹699</span>
                    </div>
                </div>
            </div>
          </div>
          </>
)
}
