import { Modal, useModal, Button, Text } from "@nextui-org/react";

export default function SizeChartModal() {
  const { setVisible, bindings } = useModal();
  return (
    <div>
      <Button auto light onPress={() => setVisible(true)}>
        Size Chart
      </Button>
      <Modal
        scroll
        width="600px"
        className="pl-5"
        aria-labelledby="modal-title"
        aria-describedby="modal-description"
        {...bindings}
      >
        <Modal.Header>
          <Text id="modal-title" size={18}>
            <b>Size Chart in Inches</b>
          </Text>
        </Modal.Header>
        <Modal.Body>
        <table className="text-center">
            <caption><b>MENS ROUND NECK T-SHIRT</b></caption>
            <thead>
              <tr>
                <th>SIZE</th>
                <th>CHEST</th>
                <th>LENGTH</th>
                <th>SLEEVE</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td>S</td>
                <td>38</td>
                <td>26</td>
                <td>7</td>
              </tr>
              <tr>
                <td>M</td>
                <td>40</td>
                <td>27</td>
                <td>7.5</td>
              </tr>
              <tr>
                <td>L</td>
                <td>42</td>
                <td>28</td>
                <td>8</td>
              </tr>
              <tr>
                <td>XL</td>
                <td>44</td>
                <td>29</td>
                <td>8.5</td>
              </tr>
              <tr>
                <td>2XL</td>
                <td>46</td>
                <td>30</td>
                <td>9</td>
              </tr>
              <tr>
                <td>3XL</td>
                <td>48</td>
                <td>31</td>
                <td>9.5</td>
              </tr>
              <tr>
                <td>4XL</td>
                <td>50</td>
                <td>32</td>
                <td>10</td>
              </tr>
              <tr>
                <td>5XL</td>
                <td>52</td>
                <td>33</td>
                <td>10</td>
              </tr>
            </tbody>
        </table>
        <table className="text-center">
          <caption><b>MENS OVERSIZE T-SHIRT</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SHOULDER</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>S</td>
              <td>42</td>
              <td>29</td>
              <td>20.5</td>
            </tr>
            <tr>
              <td>M</td>
              <td>44</td>
              <td>29.75</td>
              <td>21.25</td>
            </tr>
            <tr>
              <td>L</td>
              <td>46</td>
              <td>30.5</td>
              <td>22</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>48</td>
              <td>31.25</td>
              <td>22.75</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>50</td>
              <td>32</td>
              <td>23.5</td>
            </tr>
            <tr>
              <td>3XL</td>
              <td>52</td>
              <td>32.75</td>
              <td>24.25</td>
            </tr>
            <tr>
              <td>4XL</td>
              <td>55</td>
              <td>33.5</td>
              <td>25.5</td>
            </tr>
            <tr>
              <td>5XL</td>
              <td>58</td>
              <td>34.25</td>
              <td>26.75</td>
            </tr>
            <tr>
              <td>6XL</td>
              <td>61</td>
              <td>35</td>
              <td>28</td>
            </tr>
          </tbody>
        </table>

        <table className="text-center">
          <caption><b>WOMENS ROUND NECK T-SHIRT</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SLEEVE</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>XS</td>
              <td>36</td>
              <td>22.5</td>
              <td>5.5</td>
            </tr>
            <tr>
              <td>S</td>
              <td>38</td>
              <td>23</td>
              <td>6</td>
            </tr>
            <tr>
              <td>M</td>
              <td>40</td>
              <td>23.5</td>
              <td>6.5</td>
            </tr>
            <tr>
              <td>L</td>
              <td>42</td>
              <td>24</td>
              <td>7</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>44</td>
              <td>24.5</td>
              <td>7.5</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>46</td>
              <td>25</td>
              <td>8</td>
            </tr>
            <tr>
              <td>3XL</td>
              <td>48</td>
              <td>25.5</td>
              <td>8.5</td>
            </tr>
            <tr>
              <td>4XL</td>
              <td>50</td>
              <td>26</td>
              <td>9</td>
            </tr>
            <tr>
              <td>5XL</td>
              <td>52</td>
              <td>26.5</td>
              <td>9.5</td>
            </tr>
            <tr>
              <td>6XL</td>
              <td>54</td>
              <td>27</td>
              <td>9.5</td>
            </tr>
          </tbody>
        </table>

        <table className="text-center">
          <caption><b>WOMENS BOYFRIEND TEES</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SHOULDER</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>XS</td>
              <td>38</td>
              <td>26</td>
              <td>33.5</td>
            </tr>
            <tr>
              <td>S</td>
              <td>40</td>
              <td>27</td>
              <td>35</td>
            </tr>
            <tr>
              <td>M</td>
              <td>42</td>
              <td>27</td>
              <td>36.5</td>
            </tr>
            <tr>
              <td>L</td>
              <td>44</td>
              <td>28</td>
              <td>38</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>46</td>
              <td>28</td>
              <td>39.5</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>48</td>
              <td>29</td>
              <td>41</td>
            </tr>
            <tr>
              <td>3XL</td>
              <td>50</td>
              <td>29</td>
              <td>42.5</td>
            </tr>
            <tr>
              <td>4XL</td>
              <td>52</td>
              <td>30</td>
              <td>45</td>
            </tr>
            <tr>
              <td>5XL</td>
              <td>54</td>
              <td>32</td>
              <td>47.5</td>
            </tr>
            <tr>
              <td>6XL</td>
              <td>56</td>
              <td>33</td>
              <td>50</td>
            </tr>
          </tbody>
        </table>

        <table className="text-center">
          <caption><b>MENS VEST</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SHOULDER</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>S</td>
              <td>38</td>
              <td>27</td>
              <td>24</td>
            </tr>
            <tr>
              <td>M</td>
              <td>40</td>
              <td>28</td>
              <td>25.5</td>
            </tr>
            <tr>
              <td>L</td>
              <td>42</td>
              <td>29</td>
              <td>27</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>44</td>
              <td>30</td>
              <td>28.5</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>46</td>
              <td>30.5</td>
              <td>30</td>
            </tr>
            <tr>
              <td>3XL</td>
              <td>48</td>
              <td>31</td>
              <td>33.5</td>
            </tr>
            <tr>
              <td>4XL</td>
              <td>50</td>
              <td>31.5</td>
              <td>34.5</td>
            </tr>
            <tr>
              <td>5XL</td>
              <td>52</td>
              <td>32</td>
              <td>36.5</td>
            </tr>
            <tr>
              <td>6XL</td>
              <td>54</td>
              <td>32.5</td>
              <td>38.5</td>
            </tr>
          </tbody>
        </table>

        <table className="text-center">
          <caption><b>MENS OVERSIZE T-SHIRT</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SHOULDER</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>S</td>
              <td>38</td>
              <td>29</td>
              <td>20.5</td>
            </tr>
            <tr>
              <td>M</td>
              <td>40</td>
              <td>29.75</td>
              <td>21.25</td>
            </tr>
            <tr>
              <td>L</td>
              <td>42</td>
              <td>30.5</td>
              <td>22</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>44</td>
              <td>31.25</td>
              <td>22.75</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>46</td>
              <td>32</td>
              <td>23.5</td>
            </tr>
          </tbody>
        </table>

        <table className="text-center">
          <caption><b>HOODIES</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SLEEVE</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>S</td>
              <td>39</td>
              <td>24</td>
              <td>21.5</td>
            </tr>
            <tr>
              <td>M</td>
              <td>41</td>
              <td>25</td>
              <td>22</td>
            </tr>
            <tr>
              <td>L</td>
              <td>43</td>
              <td>26</td>
              <td>22.5</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>45</td>
              <td>27</td>
              <td>23</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>47</td>
              <td>28</td>
              <td>23.5</td>
            </tr>
          </tbody>
        </table>

        <table className="text-center">
          <caption><b>SWEAT SHIRT</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SLEEVE</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>S</td>
              <td>39</td>
              <td>24</td>
              <td>21.5</td>
            </tr>
            <tr>
              <td>M</td>
              <td>41</td>
              <td>25</td>
              <td>22</td>
            </tr>
            <tr>
              <td>L</td>
              <td>43</td>
              <td>26</td>
              <td>22.5</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>45</td>
              <td>27</td>
              <td>23</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>47</td>
              <td>28</td>
              <td>23.5</td>
            </tr>
          </tbody>
        </table>

        <table className="text-center">
          <caption><b>WOMENS CROP TOP</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SLEEVE</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>XS</td>
              <td>34</td>
              <td>17.5</td>
              <td>5.5</td>
            </tr>
            <tr>
              <td>S</td>
              <td>36</td>
              <td>18.5</td>
              <td>6</td>
            </tr>
            <tr>
              <td>M</td>
              <td>38</td>
              <td>19.5</td>
              <td>6.5</td>
            </tr>
            <tr>
              <td>L</td>
              <td>40</td>
              <td>20.5</td>
              <td>7</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>42</td>
              <td>21</td>
              <td>7.5</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>44</td>
              <td>21</td>
              <td>8</td>
            </tr>
          </tbody>
        </table>

        <table className="text-center">
          <caption><b>WOMENS CROP TOP HOODIES</b></caption>
          <thead>
            <tr>
              <th>SIZE</th>
              <th>CHEST</th>
              <th>LENGTH</th>
              <th>SLEEVE</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>XS</td>
              <td>34</td>
              <td>17.5</td>
              <td>22</td>
            </tr>
            <tr>
              <td>S</td>
              <td>36</td>
              <td>18.5</td>
              <td>23</td>
            </tr>
            <tr>
              <td>M</td>
              <td>38</td>
              <td>19.5</td>
              <td>24</td>
            </tr>
            <tr>
              <td>L</td>
              <td>40</td>
              <td>20.5</td>
              <td>25</td>
            </tr>
            <tr>
              <td>XL</td>
              <td>42</td>
              <td>21</td>
              <td>26</td>
            </tr>
            <tr>
              <td>2XL</td>
              <td>44</td>
              <td>21</td>
              <td>26</td>
            </tr>
          </tbody>
        </table>


        </Modal.Body>
        <Modal.Footer>
          <Button auto css={{backgroundColor: "#FFA000"}} onPress={() => setVisible(false)}>
            Close
          </Button>
        </Modal.Footer>
      </Modal>
    </div>
  );
}
