import Head from "next/head";
import AdminLayout from "@/components/layout-admin";
import axios from "axios";
import Link from "next/link"; 
import Image from "next/image";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";
import { isTokenValid, getRole } from "@/utils/JWTVerifier";
import PayoutConfirm from "@/components/payout-confirm";
import {uuidv4} from "@firebase/util";
import {Button, Grow, Paper} from "@mui/material";

export default function AdminCancelOrdersPage() {
  const [tokenExists, setTokenExists] = useState(false);
  const router = useRouter();
  let isReady = router.isReady;
  const [pageNo, setPage] = useState(0);
  const [pageSize, setPageSize] = useState(0);
//   const [cancelOrders, setCancelOrders] = useState([]);

//   useEffect(() => {
//     fetch('/api/cancelOrders')
//       .then(response => response.json())
//       .then(data => setCancelOrders(data));
//   }, []);
useEffect(() => {
  const jwtToken = localStorage.getItem("token");
  if (jwtToken === undefined || !isTokenValid(jwtToken) || getRole(jwtToken) !== 'ROLE_ADMIN')
    router.push("/admin");
  else
    setTokenExists(true);
  
}, []);

  return (
    <>
      <Head>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/logo.png' />
        <title>Madrasda | Cancel Orders</title>
      </Head>

      {tokenExists && (
        <AdminLayout>
          <main
            className='body-font overflow-hidden font-quest
                                md:ml-32'>
            <div className='px-5 my-10 mx-auto'>
              <h1
                className='text-3xl text-primary 
                               md:ml-20 md:mt-10'>
                CANCEL REQUESTS
              </h1>
            </div>
            <Grow in timeout={600 % (600 * 5)}>
              <div className='flex flex-col -mb-5'>
                <Paper
                  className='container bg-gray ml-28 mt-8 py-4 w-5/6 rounded-md'
                  elevation={3}>
                  <div className=' ml-8 mr-20 mt-4'>
                    <h1 className='text-2xl text-primary mb-6 py-2'>
                      Customer Phone: 7001234567
                    </h1>
                    <div className='flex w-full justify-between mb-2'>
                      <h2 className='mb-2 text-lg font-medium text-black flex items-center'>
                        Order Status : Confirmed
                      </h2>
                      <h2 className='mb-2 text-lg font-medium text-black flex items-center'>
                        Order Date : 69/69/69
                      </h2>
                      <h2 className='mb-2 text-lg font-medium text-black flex items-center'>
                        Order Items : 2 N
                      </h2>
                    </div>
                    <div className='flex w-full justify-between mb-2'>
                      <h2 className='mb-2 text-lg font-medium text-black flex items-center'>
                        Reason : Wrong Size
                      </h2>
                      <h2 className='mb-2 text-lg font-medium text-black flex items-center'>
                        Order Total : ₹7xx
                      </h2>
                    </div>
                    <div className='flex justify-end space-x-4'>
                      <Button variant='outlined' color='error'>
                        Delete
                      </Button>
                      <Button variant='outlined' color='success'>
                        Accept
                      </Button>
                    </div>
                  </div>
                </Paper>
              </div>
            </Grow>
            {
              // queries && queries.length !== 0 &&
              <div className='flex justify-center mt-32'>
                <button
                  className='bg-[#fab337] hover:bg-[#ffa200] text-white font-small py-2 px-5 rounded mr-6'
                  onClick={() => {
                    setPage(pageNo === 0 ? 0 : pageNo - 1);
                  }}>
                  Prev
                </button>
                <button
                  className='bg-[#fab337] hover:bg-[#ffa200] text-white font-small py-2 px-5 rounded ml-6'
                  onClick={() => {
                    setPage(pageNo === pageSize - 1 ? pageNo : pageNo + 1);
                  }}>
                  Next
                </button>
              </div>
            }
          </main>
        </AdminLayout>
      )}
    </>
  );
};
