import Head from "next/head";
import SearchVendor from "@/components/search-vendor";
import Payments from "@/components/payments";
import AdminLayout from "@/components/layout-admin";
import axios from "axios";
import { useEffect } from "react";
import { useRouter } from "next/router";
import { isTokenValid } from "@/utils/JWTVerifier";

export default function CustomerDetails () {
  const [tokenExists, setTokenExists] = useState(false)
  const router = useRouter();

  useEffect(() => {
    const jwtToken = localStorage.getItem("token")
    if(jwtToken === undefined || !isTokenValid(jwtToken))
      router.push("/admin");
    else
      setTokenExists(true);
  }, []);
  
    return (
        <>
            <Head>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/logo.png" />
            <title>Madrasda | Customer Details</title>
            </Head>

            <AdminLayout>
                <main className="body-font md:ml-32 overflow-hidden font-algeria">
                <div className="px-5 my-10 mx-auto">
                <h1 className="text-3xl text-primary md:ml-20 md:mt-10">CUSTOMER DETAILS</h1>
                <div className='mt-4 md:ml-20'>
                    <Payments />
                </div>
                </div>
                </main>
            </AdminLayout>
        </>
    )
}