import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { isTokenValid } from '@/utils/JWTVerifier'
import { useEffect, useState } from 'react'
import axios from "axios";
import { useRouter } from 'next/router'

export default function Adminlogin() {
    const [mail,setEmail]=useState();
    const [password,setPassword]=useState();
    const router = useRouter();

    const adminlogin = (e) =>{
        e.preventDefault();
        axios
          .post('http://localhost:8080/api/auth/loginAdmin', {
            email: mail,
            password: password
          })
          .then((response) => {
            localStorage.setItem("token", response.data.token);
            router.push("/admin/vendorlist");
          })
          .catch((err)=>{
            alert(err.response.data.message);
          })
          ;
    }

  useEffect(() => {
        const token = localStorage.getItem("token")
        if (token && isTokenValid(token))
            router.push("/admin/vendorlist");
    }, [])

  return (
    <>
    <Head>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <title>Madrasda | Login</title>
      </Head>
      <div className="bg-center bg-no-repeat bg-cover flex bg-[url(https://cdn.discordapp.com/attachments/812329575953858620/1078262102269104199/Login.png)] w-screen h-screen">
            <div className='w-full bg-cover bg-center flex-center flex-row bg-transparent max-w-md m-auto backdrop-blur-md bg-black/60 rounded-3xl drop-shadow-2xl py-8 px-16'>
            <div className="flex flex-wrap justify-center">
                <div className="w-24">
                    <img src="/logo.png" alt="LOGO"/>
                </div>
            </div>
            <div className='flex flex-wrap mt-2 justify-center'>
            </div>
            <h1 className='text-2xl text-white font-medium mt-2 mb-12 text-center'>
                LOGIN
            </h1>
                <form onSubmit={adminlogin}>
                    <div className='text-xl text-[#A5153F] m-2 text-center' id="responsesection"></div>
                    <div>
                        <label htmlFor='email' className='text-white'>Username</label>
                        <input
                            type='email'
                            className={'w-full p-2 text-primary rounded-md outline-none text-sm transition duration-150 ease-in-out mb-4'}
                            id='username'
                            placeholder='example@example.com' onChange={(e)=>setEmail(e.target.value)}
                        />
                    </div>
                    <div>
                        <label htmlFor='password' className='text-white'>Password</label>
                        <input
                            type='password'
                            className={'w-full p-2 text-primary rounded-md outline-none text-sm transition duration-150 ease-in-out mb-4'}
                            id='password'
                            placeholder='**********'
                            onChange={(e) => setPassword(e.target.value)}
                        />
                    </div>
                    <div className='flex justify-center items-center mt-6'>
                        <div>
                        <button type="submit" className={`bg-[#A5153F] cursor-pointer py-2 px-5 text-l text-white rounded focus:outline-none `}
                        >
                            Login
                        </button>
                        </div>
                    </div>
                </form>
            <br/>
            </div>
        </div>
    </>
  )
}
