import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import SearchVendor from "@/components/search-vendor";
import AdminLayout from "@/components/layout-admin";
import AdminUploadModal from "@/components/adminuploadmodal";
import { useState, useEffect, useRef } from "react";
import axios from 'axios';


export default function MyProducts() {



    const [token, setToken] = useState();
    const [mockuplist, setmockuplist] = useState([]);
    const [pageNo, setPageNo] = useState(0);
   
    useEffect(() => {
        // loader will be called here....
        // if (sessionStorage.getItem('token')) {
        //     setToken(sessionStorage.getItem('token'));
        //     // console.log(token);
        // }
        // else {
        //     window.location.href = '/admin';
        // }
        axios.get('http://localhost:8080/api/mockup/getAllMockups?pageNo=' + pageNo)
            .then((response) => {

                setmockuplist(response.data.content);
                console.log(mockuplist)
                if (response.status === 200) {
                    // console.log(response.data);
                }
            })
            .catch((err) => {
                console.log(err);
            });

    }, [])
    return (
        <>
            <Head>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/logo.png" />
                <title>Madrasda | My Products</title>
            </Head>

            <AdminLayout>
                <section className="body-font overflow-hidden font-algeria
                            md:ml-32">
                    <div className="px-5 my-10 mx-auto">
                        <h1 className="text-3xl text-primary 
                           md:ml-20">MY PRODUCTS</h1>
                        <div className="flex items-center justify-center m-5">
                            <SearchVendor />
                        </div>
                        <div className="flex flex-wrap justify-center">

                            <div className="lg:w-1/4 md:w-1/2 p-4 w-full h-96 flex items-center justify-center m-5 rounded duration-200 ease-in-out">
                                <Link href="#" >
                                    <div className="flex flex-col items-center justify-center cursor-pointer">
                                        <AdminUploadModal />
                                        <p className="font-semibold font-base">Upload Mockup</p>
                                        <p className="font-light text-gray font-sm">Add them to your product list for vendors</p>
                                    </div>
                                </Link>
                            </div>
                            {mockuplist.map((mockup)=>(
                                 <div className="lg:w-1/4 md:w-1/2 p-4 w-full h-full cursor-pointer bg-off-white m-5 rounded drop-shadow-[4px_4px_10px_rgba(0,0,0,0.2)] hover:drop-shadow-[8px_8px_4px_rgba(0,0,0,0.3)] duration-200 ease-in-out">
                                 <span className="w-full text-gray flex justify-end">x</span>
                                 <a className="block relative h-fit rounded overflow-hidden">
                                     <Image src="/v-tee.png"
                                         alt="ecommerce"
                                         height={1080}
                                         width={1920}
                                         className="object-contain object-center w-full h-full" />
                                 </a>
                                 <div className="mt-4">
                                     <h3 className="text-base title-font">{mockup.name}</h3>
                                     {/* <div className="flex">
                                         <h2 className="title-font text-sm text-gray">Technique:</h2>
                                         <p className="pl-1 text-gray text-sm">PRINT</p>
                                     </div> */}
                                     <span className="mt-1 text-gray pr-1 text-sm">Sizes:</span>
                                     <span className="mt-1 text-gray pr-1 text-sm">S,M,L,XL,XXL,XXXL,4XL,5XL </span>
                                 </div>
                             </div>
                            ))}

                            {/* <div className="lg:w-1/4 md:w-1/2 p-4 w-full h-full cursor-pointer bg-off-white m-5 rounded drop-shadow-[4px_4px_10px_rgba(0,0,0,0.2)] hover:drop-shadow-[8px_8px_4px_rgba(0,0,0,0.3)] duration-200 ease-in-out">
                                <span className="w-full text-gray flex justify-end">x</span>
                                <a className="block relative h-fit rounded overflow-hidden">
                                    <Image src="/v-tee.png"
                                        alt="ecommerce"
                                        height={1080}
                                        width={1920}
                                        className="object-contain object-center w-full h-full" />
                                </a>
                                <div className="mt-4">
                                    <h3 className="text-base title-font">Vikram Hoodies</h3>
                                    <div className="flex">
                                        <h2 className="title-font text-sm text-gray">Technique:</h2>
                                        <p className="pl-1 text-gray text-sm">PRINT</p>
                                    </div>
                                    <span className="mt-1 text-gray pr-1 text-sm">Sizes:</span>
                                    <span className="mt-1 text-gray pr-1 text-sm">S,M,L,XL,XXL,XXXL,4XL,5XL </span>
                                </div>
                            </div>

                            <div className="lg:w-1/4 md:w-1/2 p-4 w-full h-full cursor-pointer bg-off-white m-5 rounded drop-shadow-[4px_4px_10px_rgba(0,0,0,0.2)] hover:drop-shadow-[8px_8px_4px_rgba(0,0,0,0.3)] duration-200 ease-in-out">
                                <span className="w-full text-gray flex justify-end">x</span>
                                <a className="block relative h-fit rounded overflow-hidden">
                                    <Image src="/v-tee.png"
                                        alt="ecommerce"
                                        height={1080}
                                        width={1920}
                                        className="object-contain object-center w-full h-full" />
                                </a>
                                <div className="mt-4">
                                    <h3 className="text-base title-font">Vikram Hoodies</h3>
                                    <div className="flex">
                                        <h2 className="title-font text-sm text-gray">Technique:</h2>
                                        <p className="pl-1 text-gray text-sm">PRINT</p>
                                    </div>
                                    <span className="mt-1 text-gray pr-1 text-sm">Sizes:</span>
                                    <span className="mt-1 text-gray pr-1 text-sm">S,M,L,XL,XXL,XXXL,4XL,5XL </span>
                                </div>
                            </div>

                            <div className="lg:w-1/4 md:w-1/2 p-4 w-full h-full cursor-pointer bg-off-white m-5 rounded drop-shadow-[4px_4px_10px_rgba(0,0,0,0.2)] hover:drop-shadow-[8px_8px_4px_rgba(0,0,0,0.3)] duration-200 ease-in-out">
                                <span className="w-full text-gray flex justify-end">x</span>
                                <a className="block relative h-fit rounded overflow-hidden">
                                    <Image src="/v-tee.png"
                                        alt="ecommerce"
                                        height={1080}
                                        width={1920}
                                        className="object-contain object-center w-full h-full" />
                                </a>
                                <div className="mt-4">
                                    <h3 className="text-base title-font">Vikram Hoodies</h3>
                                    <div className="flex">
                                        <h2 className="title-font text-sm text-gray">Technique:</h2>
                                        <p className="pl-1 text-gray text-sm">PRINT</p>
                                    </div>
                                    <span className="mt-1 text-gray pr-1 text-sm">Sizes:</span>
                                    <span className="mt-1 text-gray pr-1 text-sm">S,M,L,XL,XXL,XXXL,4XL,5XL </span>
                                </div>
                            </div>

                            <div className="lg:w-1/4 md:w-1/2 p-4 w-full h-full cursor-pointer bg-off-white m-5 rounded drop-shadow-[4px_4px_10px_rgba(0,0,0,0.2)] hover:drop-shadow-[8px_8px_4px_rgba(0,0,0,0.3)] duration-200 ease-in-out">
                                <span className="w-full text-gray flex justify-end">x</span>
                                <a className="block relative h-fit rounded overflow-hidden">
                                    <Image src="/v-tee.png"
                                        alt="ecommerce"
                                        height={1080}
                                        width={1920}
                                        className="object-contain object-center w-full h-full" />
                                </a>
                                <div className="mt-4">
                                    <h3 className="text-base title-font">Vikram Hoodies</h3>
                                    <div className="flex">
                                        <h2 className="title-font text-sm text-gray">Technique:</h2>
                                        <p className="pl-1 text-gray text-sm">PRINT</p>
                                    </div>
                                    <span className="mt-1 text-gray pr-1 text-sm">Sizes:</span>
                                    <span className="mt-1 text-gray pr-1 text-sm">S,M,L,XL,XXL,XXXL,4XL,5XL </span>
                                </div>
                            </div>

                            <div className="lg:w-1/4 md:w-1/2 p-4 w-full h-full cursor-pointer bg-off-white m-5 rounded drop-shadow-[4px_4px_10px_rgba(0,0,0,0.2)] hover:drop-shadow-[8px_8px_4px_rgba(0,0,0,0.3)] duration-200 ease-in-out">
                                <span className="w-full text-gray flex justify-end">x</span>
                                <a className="block relative h-fit rounded overflow-hidden">
                                    <Image src="/v-tee.png"
                                        alt="ecommerce"
                                        height={1080}
                                        width={1920}
                                        className="object-contain object-center w-full h-full" />
                                </a>
                                <div className="mt-4">
                                    <h3 className="text-base title-font">Vikram Hoodies</h3>
                                    <div className="flex">
                                        <h2 className="title-font text-sm text-gray">Technique:</h2>
                                        <p className="pl-1 text-gray text-sm">PRINT</p>
                                    </div>
                                    <span className="mt-1 text-gray pr-1 text-sm">Sizes:</span>
                                    <span className="mt-1 text-gray pr-1 text-sm">S,M,L,XL,XXL,XXXL,4XL,5XL </span>
                                </div>
                            </div> */}

                        </div>
                    </div>
                </section>
            </AdminLayout>
        </>
    );
}