import Head from 'next/head'
import AdminLayout from '@/components/layout-admin'
import Accordian from '@/components/accordian'

export default function Queries () {
  return (
    <>
    <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logo.png" />
        <title>Madrasda | Queries</title>
    </Head>
    
    <AdminLayout>
    <main className='ml-32 overflow-hidden font-algeria'>
    <div className="px-5 my-10 mx-auto">
        <div className="ml-20 mt-10">
          <h1 className="body-font text-primary text-3xl">QUERIES AND FEEDBACK</h1>
        </div>

        <hr className="h-px ml-20 mr-12 my-6 bg-black border-1"></hr>
        
        <div className="ml-32"> 
            <h1 className="title-font font-medium text-2xl pb-8">1.Post your Queries:</h1>
            <div className=" mt-14 flex justify-center ">
                <button type="button" className="text-white bg-black hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2">Save as Draft</button>
                <button type="button" className="text-white bg-primary hover:bg-blue-800 focus:outline-none focus:ring-4 focus:ring-blue-300 font-medium rounded-full text-sm px-5 py-2.5 text-center mr-2 mb-2">Upload Query</button>
            </div>
        </div>

        <hr className="h-px ml-20 mr-12 my-6 bg-black border-1"></hr>
        
        <div className="ml-32"> 
            <h1 className="title-font font-medium text-2xl pb-8">2.FAQ:</h1>
            <Accordian />
        </div>
    </div>
    </main>
    </AdminLayout>
    </>
  )
}
