import Image from "next/image";
import Head from "next/head";
import AdminLayout from "@/components/layout-admin";

export default function Replacements () {
  return (
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.png" />
      <title>Madrasda | Replacements</title>
    </Head>
    
    <AdminLayout>
    <section className="body-font font-algeria
                        md:ml-32">
      <div className="px-5 py-24 mx-auto">
      </div>
    </section>
    </AdminLayout>
    </>
  );
}