import Image from "next/image";
import Head from "next/head";
import Link from "next/link";
import SearchVendor from "@/components/search-vendor";
import AdminLayout from "@/components/layout-admin";
import AddVendorModal from "@/components/addvendor-modal";
import { useEffect, useState,useRef } from "react";
import axios from 'axios';

export default function VendorList () {
  const [token, setToken] = useState();
  const [vendorlist,setvendorlist]= useState([]);
  // const img='';
  useEffect(() => {
    // loader will be called here....
    if (sessionStorage.getItem('token')) {
      setToken(sessionStorage.getItem('token'));
      // console.log(token);
    }
    else {
      window.location.href = '/admin';
    }

    axios
      .get('http://localhost:8080/api/admin/getVendors')
      .then((response) => {
        // console.log(response.data);
        setvendorlist(response.data);
        console.log(vendorlist)
          // if(response.status === 200) {
          //     console.log(response.data);
          // }
      })
      .catch((err)=>{
        console.log(err);
    });

  }, [])

  return (
    <>
    <Head>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/logo.png" />
      <title>Madrasda | Vendor List</title>
    </Head>
    
    <AdminLayout>
    <section className="body-font overflow-hidden font-algeria
                        md:ml-32">
      <div className="px-5 my-10 mx-auto">
        <h1 className="text-3xl text-primary 
                       md:ml-20">MY VENDORS</h1>
        <div className="flex items-center justify-end m-5 mt-0">
          <SearchVendor />
        </div>
        <div className="flex flex-wrap justify-center">
        {vendorlist.map((i) => (
        <div id={i.id} className="lg:w-1/6 md:w-1/2 p-4 min-h-full w-4/6 h-fit cursor-pointer bg-off-white m-5 rounded drop-shadow-[4px_4px_10px_rgba(0,0,0,0.2)] hover:drop-shadow-[8px_8px_4px_rgba(0,0,0,0.3)] duration-200 ease-in-out">
          <Link href="/admin/vendordetails">
            <div className="block relative h-fit rounded overflow-hidden">
                <Image
                //  src="/myvendor-vikram.png" 
                loader={() => {i.imgUrl}}
                src={i.imgUrl}
                alt={i.name+" img"}
                height={300}
                width={300} 
                className="object-contain object-center w-full h-full" />
            </div>
            <h3 className="text-base font-bold title-font mt-4 text-center flex justify-center items-center">{i.name}</h3>
          </Link>
        </div>))}
        
        

        {/* <div className="lg:w-1/6 md:w-1/2 p-4 min-h-full w-4/6 h-fit cursor-pointer bg-off-white m-5 rounded drop-shadow-[4px_4px_10px_rgba(0,0,0,0.2)] hover:drop-shadow-[8px_8px_4px_rgba(0,0,0,0.3)] duration-200 ease-in-out">
          <Link href="/admin/vendordetails">
            <div className="block relative h-fit rounded overflow-hidden">
                <Image src="/myvendor-redgiant.png" 
                alt="ecommerce" 
                height={1080}
                width={1920} 
                className="object-contain object-center w-full h-full" />
            </div>
            <h3 className="text-base font-bold title-font mt-4 text-center flex justify-center items-center">RED GIANT PRODUCTIONS</h3>
          </Link>
        </div> */}

        <div className="lg:w-1/6 md:w-1/2 p-4 w-4/6 lg:h-80 md:h-96 h-80 flex items-center justify-center m-5 rounded duration-200 ease-in-out">  
          <Link href="#" >
          <div className="flex flex-col items-center justify-center cursor-pointer">
            <AddVendorModal/>
            <p className="font-semibold text-base text-center">Add new vendor</p>
            <p className="font-light text-gray text-sm text-center">Add new vendors to your list</p>
          </div>
          </Link>
        </div>

        </div>
      </div>
    </section>
    </AdminLayout>
    </>
  );
}